

TRAIN = 0.7
VALID = 0.2
TEST = 1 - TRAIN - VALID
REPETICIONES_DESORDENAR = 1000

NARANJAS_FRESCA = 'naranjas_frescas'
NARANJAS_NOFRESCA = 'naranjas_nofrescas'

RUTA_FUENTE_IMAGENES = '/backup/.personal/UNI/2022-II/IA/TRABAJO-FINAL/Augmented Image'
RUTA_FUENTE_NARANJAS_FRESCAS = RUTA_FUENTE_IMAGENES + '/FreshOrange'
RUTA_FUENTE_NARANJAS_NOFRESCAS = RUTA_FUENTE_IMAGENES + '/RottenOrange'

RUTA_DESTINO = '/backup/.personal/UNI/2022-II/IA/TRABAJO-FINAL/dataset'
RUTA_DESTINO_TRAIN = RUTA_DESTINO + '/train'
RUTA_DESTINO_VALID = RUTA_DESTINO + '/valid'
RUTA_DESTINO_TEST = RUTA_DESTINO + '/test'

RUTA_DESTINO_NARANJAS_FRESCAS = RUTA_DESTINO + '/' + NARANJAS_FRESCA
RUTA_DESTINO_NARANJAS_NOFRESCAS = RUTA_DESTINO + '/' + NARANJAS_NOFRESCA
