

TRAIN = 0.8
VALID = 0.1
TEST = 1 - TRAIN - VALID
REPETICIONES_DESORDENAR = 1000

NARANJAS_FRESCA = 'buenas'
NARANJAS_NOFRESCA = 'malas'

RUTA_FUENTE_IMAGENES = './FUENTE-NARANJAS'
RUTA_FUENTE_NARANJAS_FRESCAS = RUTA_FUENTE_IMAGENES + '/' + NARANJAS_FRESCA
RUTA_FUENTE_NARANJAS_NOFRESCAS = RUTA_FUENTE_IMAGENES + '/' + NARANJAS_NOFRESCA

RUTA_DESTINO = './dataset'
RUTA_DESTINO_TRAIN = RUTA_DESTINO + '/train'
RUTA_DESTINO_VALID = RUTA_DESTINO + '/valid'
RUTA_DESTINO_TEST = RUTA_DESTINO + '/test'

RUTA_DESTINO_NARANJAS_FRESCAS = RUTA_DESTINO + '/' + NARANJAS_FRESCA
RUTA_DESTINO_NARANJAS_NOFRESCAS = RUTA_DESTINO + '/' + NARANJAS_NOFRESCA
